
# -*- makefile -*-
# Do not edit this file.
# This file will be overwritten by the project setup script.

RAW_SIMICS_BASE=/home/elias/Documents/arqui/taller_simes/simics-6.0.166
RAW_SIMICS_MODEL_BUILDER=/home/elias/Documents/arqui/taller_simes/simics-6.0.166
RAW_EML_PACKAGE=
RAW_DODOC_PKG=/home/elias/Documents/arqui/taller_simes/simics-6.0.166

RAW_SIMICS_PACKAGE_LIST=/home/elias/Documents/arqui/taller_simes/simics-6.0.166/.package-list

INCLUDE_PATHS = /home/elias/Documents/arqui/taller_simes/simics-6.0.166/src/include
CXX_INCLUDE_PATHS = /home/elias/Documents/arqui/taller_simes/simics-6.0.166/linux64/api
DML_INCLUDE_PATHS = /home/elias/Documents/arqui/taller_simes/simics-6.0.166/linux64/bin/dml/api
HOST_TYPE = linux64
