#!/bin/bash
# this file will be overwritten by the project setup script
SIMICS_BASE_PACKAGE="/home/kevin/Desktop/SIMICS/simics-6.0.166"
export SIMICS_BASE_PACKAGE
if [ -f "/home/kevin/Desktop/canny-edge-detector/simics-project/.package-list" ]; then
    exec "/home/kevin/Desktop/SIMICS/simics-6.0.166/bin/simics-eclipse" --package-list "/home/kevin/Desktop/canny-edge-detector/simics-project/.package-list" --project "/home/kevin/Desktop/canny-edge-detector/simics-project" "$@"
else
    exec "/home/kevin/Desktop/SIMICS/simics-6.0.166/bin/simics-eclipse" --project "/home/kevin/Desktop/canny-edge-detector/simics-project" "$@"
fi
